# Generated by Django 4.2 on 2025-05-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="День недели",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(blank=True, null=True, verbose_name="Время"),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Место"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Действие"
                    ),
                ),
                (
                    "pleasent",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "publicity",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "execution_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Время на выполнение"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Награда"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("m x-y * * *", "every hour"),
                            ("m x-y/2 * * *", "every 2 hours"),
                            ("m x-y/3 * * *", "every 3 hours"),
                            ("m x,z,y * * *", "3 times per day"),
                            ("m x,y * * *", "2 times per day"),
                            ("m h * * *", "every day"),
                            ("m h */2 * *", "every 2 days"),
                            ("m h */3 * *", "every 3 days"),
                            ("m h * * d", "selected days"),
                        ],
                        default="m h * * *",
                        max_length=50,
                        null=True,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время последнего выполнения привычки за день",
                    ),
                ),
                (
                    "days_of_week",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="habits_tracker.day",
                        verbose_name="День недели",
                    ),
                ),
                (
                    "related_habits",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits_tracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
